export const ADD_POST = "ADD_POST";
export const DELETE_POST = "DELETE_POST";
export const EDIT_POST = "EDIT_POST";

export const FETCH_ADD_POST = "FETCH_ADD_POST";
export const POST_NEW_POST = "POST_NEW_POST";
export const DELETE_FETCH_POST = "DELETE_FETCH_POST";
export const FETCH_EDIT_POST = "FETCH_EDIT_POST";

export const AXIOS_ADD_POST = "AXIOS_ADD_POST";
export const POST_NEW_POST_AXIOS = "POST_NEW_POST_AXIOS";
export const DELETE_AXIOS_POST = "DELETE_AXIOS_POST";
export const AXIOS_EDIT_POST = "AXIOS_EDIT_POST";